import {
    HomeIcon,
    ViewListIcon,
    ArrowLeftIcon,
    CalendarIcon,
    CogIcon,
    UsersIcon,
    MailIcon,
    UserCircleIcon,
    IdentificationIcon,
    OfficeBuildingIcon,
    AdjustmentsIcon,
} from "@heroicons/react/outline";

export const navigation = [
    {
        name: "ダッシュボード",
        href: "/host",
        Icon: HomeIcon,
        roles: ["host"],
    },
    {
        name: "ダッシュボード",
        href: "/admin",
        Icon: HomeIcon,
        roles: ["admin"],
    },
    {
        name: "アカウント管理",
        href: "/admin/accounts",
        Icon: UsersIcon,
        roles: ["admin"],
    },
    {
        name: "ホスト管理",
        href: "/admin/hosts",
        Icon: UsersIcon,
        roles: ["admin"],
    },
    {
        name: "システム設定",
        href: "/admin/settings/",
        Icon: CogIcon,
        roles: ["admin"],
    },
    {
        name: "プロフィール",
        href: "/user/profile",
        Icon: UserCircleIcon,
        roles: ["user"],
    },
    {
        name: "プロフィール",
        href: "/user/profile",
        Icon: UserCircleIcon,
        roles: ["host"],
    },
    {
        name: "サブスクリプション",
        href: "/user/subscriptions",
        Icon: CalendarIcon,
        roles: ["user"],
    },
    {
        name: "設定",
        href: "/user/settings",
        Icon: CogIcon,
        roles: ["user"],
    },
    {
        name: "予約",
        href: "/user/reservation",
        Icon: CalendarIcon,
        roles: ["user"],
    },
    {
        name: "予約",
        href: "/host/reservation",
        Icon: CalendarIcon,
        roles: ["host"],
    },
    {
        name: "メッセージ",
        href: "/messages",
        Icon: MailIcon,
        roles: ["user", "host"],
    },
    {
        name: "施設管理",
        href: "/host/my-space",
        Icon: ViewListIcon,
        roles: ["host"],
    },

    {
        name: "宿泊管理",
        href: "/host/hotel-space",
        Icon: OfficeBuildingIcon,
        roles: ["host"],
    },
    {
        name: "オプション管理",
        href: "/host/options",
        Icon: AdjustmentsIcon,
        roles: ["host"],
    },
    {
        name: "キャンセルポリシー管理",
        href: "/host/cancelPolicies",
        Icon: CalendarIcon,
        roles: ["host"],
    },
    {
        name: "ライセンス管理",
        href: "/host/license",
        Icon: IdentificationIcon,
        roles: ["host"],
    },
    {
        name: "トップに戻る",
        href: "/",
        Icon: ArrowLeftIcon,
        roles: ["user", "host", "admin"],
    },
];
